services:
  - type: web
    name: dll-lmstc
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn DLL_LMSTC.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: "dll-lmstc-gza7.onrender.com"
      - key: RENDER
        value: True
      - key: DATABASE_URL
        value: "postgresql://postgres.bqlgmcqbwpdeinsxtffk:12124124%40Perez22@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require"
