# Generated by Django 5.1.7 on 2025-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0003_emailaddress_socialaccount_usergroup_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('program_detail', models.CharField(max_length=255)),
                ('program_sched', models.CharField(max_length=255)),
            ],
        ),
    ]
