# Generated by Django 5.1.7 on 2025-05-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0005_programimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
                ('availability', models.CharField(choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months')], max_length=20)),
                ('skills', models.JSONField(default=list)),
                ('email_or_link', models.CharField(max_length=300)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Applicant.programs')),
            ],
        ),
    ]
