# Generated by Django 5.1.7 on 2025-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0006_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
