# Generated by Django 5.1.7 on 2025-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0008_programapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uli_number', models.CharField(blank=True, max_length=100, verbose_name='Unique Learner Identifier')),
                ('entry_date', models.DateField(verbose_name='Entry Date')),
                ('last_name', models.CharField(max_length=100)),
                ('extension_name', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, verbose_name='City / Municipality')),
                ('barangay', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255, verbose_name='House No., Street, Subdivision/Barangay')),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widower', 'Widower'), ('Separated', 'Separated'), ('Solo Parent', 'Solo Parent')], max_length=20)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('birth_region', models.CharField(max_length=100)),
                ('birth_province', models.CharField(max_length=100)),
                ('birth_city', models.CharField(max_length=100, verbose_name='Birth City / Municipality')),
                ('educational_attainment', models.CharField(choices=[('No Grade Complete', 'No Grade Complete'), ('Pre-School', 'Pre-School(Nursery/Kinder/Prep)'), ('Elementary Undergraduate', 'Elementary Undergraduate'), ('Elementary Graduate', 'Elementary Graduate'), ('Junior Graduate', 'Junior Graduate'), ('High School Graduate', 'High School Graduate')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
