# Generated by Django 5.1.7 on 2025-05-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0009_learnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='educational_attainment',
            field=models.CharField(choices=[('No Grade Complete', 'No Grade Complete'), ('Pre-School', 'Pre-School(Nursery/Kinder/Prep)'), ('Elementary Undergraduate', 'Elementary Undergraduate'), ('Elementary Graduate', 'Elementary Graduate'), ('Junior Graduate', 'Junior Graduate'), ('High School Graduate', 'High School Graduate'), ('Post Secondary Graduate', 'Post Secondary Graduate'), ('Post Secondary Undergraduate', 'Post Secondary Undergraduate'), ('Senior High Graduate', 'Senior High Graduate'), ('College Undergraduate', 'College Undergraduate'), ('College Graduate or Higher', 'College Graduate or Higher')], max_length=50),
        ),
    ]
