# Generated by Django 5.1.7 on 2025-05-17 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0010_learnerprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='uploads/id_pictures/')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(default='Filipino', max_length=255)),
                ('sex', models.CharField(default='Not Specified', max_length=10)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=50, null=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthplace_region', models.CharField(blank=True, max_length=100, null=True)),
                ('birthplace_province', models.CharField(blank=True, max_length=100, null=True)),
                ('birthplace_city', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_guardian', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(default='', max_length=100)),
                ('classification_other', models.CharField(blank=True, max_length=255, null=True)),
                ('disability_type', models.CharField(max_length=100)),
                ('disability_cause', models.CharField(max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_package', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
