# Generated by Django 5.1.7 on 2025-05-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0011_learner_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner_profile',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='classification_other',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='disability_cause',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='disability_type',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='scholarship_package',
        ),
    ]
