# Generated by Django 5.1.7 on 2025-05-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0012_remove_learner_profile_classification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnerProfile',
        ),
    ]
