# Generated by Django 5.1.7 on 2025-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0013_delete_learnerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='course_or_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='other_classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='scholarship_package',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='Applicant.clientclassification'),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='disability_causes',
            field=models.ManyToManyField(blank=True, to='Applicant.disabilitycause'),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='disability_types',
            field=models.ManyToManyField(blank=True, to='Applicant.disabilitytype'),
        ),
    ]
