# Generated by Django 5.1.7 on 2025-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0014_clientclassification_disabilitycause_disabilitytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
