# Generated by Django 5.1.7 on 2025-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0015_educationalattainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_profile',
            name='agree_to_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='applicant_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='date_accomplished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
