# Generated by Django 5.1.7 on 2025-05-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0016_learner_profile_agree_to_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_profile',
            name='educational_attainment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicant.educationalattainment'),
        ),
    ]
