# Generated by Django 5.1.7 on 2025-05-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0017_alter_learner_profile_educational_attainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_profile',
            name='educational_attainment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Applicant.educationalattainment'),
        ),
    ]
