# Generated by Django 5.1.7 on 2025-05-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0018_alter_learner_profile_educational_attainment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner_profile',
            name='educational_attainment',
        ),
    ]
