# Generated by Django 5.1.7 on 2025-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0019_remove_learner_profile_educational_attainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
