# Generated by Django 5.1.7 on 2025-05-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0020_programapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
