# Generated by Django 5.1.7 on 2025-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0021_alter_learner_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_profile',
            name='barangay_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='province_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='region_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
