# Generated by Django 5.1.7 on 2025-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0022_learner_profile_barangay_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_profile',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
