# Generated by Django 5.1.7 on 2025-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0023_learner_profile_educational_attainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_profile',
            name='birthplace_cityb_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='birthplace_provinceb_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='birthplace_regionb_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
