# Generated by Django 5.1.7 on 2025-05-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0024_learner_profile_birthplace_cityb_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='program_skill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='program_trainor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
