# Generated by Django 5.1.7 on 2025-05-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0026_trainerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_programs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_applicants', to='Applicant.programs')),
            ],
            options={
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
