# Generated by Django 5.1.7 on 2025-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0031_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
