# Generated by Django 5.2.4 on 2025-07-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0032_programapplication_decline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
