# Generated by Django 5.2.4 on 2025-08-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0034_task_taskcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner_profile',
            name='birthplace_city',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='birthplace_province',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='birthplace_region',
        ),
        migrations.AlterField(
            model_name='learner_profile',
            name='birthplace_cityb_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learner_profile',
            name='birthplace_provinceb_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learner_profile',
            name='birthplace_regionb_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
