# Generated by Django 5.2.4 on 2025-08-28 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0035_remove_learner_profile_birthplace_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapplicant',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvedapplicant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='approvedapplicant',
            name='total_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvedapplicant',
            name='total_present',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApplicantPasser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('final_progress', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('enrollment_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_programs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_applicants', to='Applicant.programs')),
            ],
            options={
                'ordering': ['-completion_date'],
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
