# Generated by Django 5.2.4 on 2025-09-19 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0037_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('is_walkin', models.BooleanField(default=True)),
                ('queue_number', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_applications', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_walkins', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkin_applications', to='Applicant.programs')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedWalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_walkin_programs', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_walkins', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_walkins', to='Applicant.programs')),
                ('original_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='Applicant.walkinapplication')),
            ],
            options={
                'ordering': ['-approved_at'],
                'unique_together': {('applicant', 'program')},
            },
        ),
        migrations.CreateModel(
            name='WalkInPasser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('final_progress', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('enrollment_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_walkin_programs', to=settings.AUTH_USER_MODEL)),
                ('original_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='Applicant.walkinapplication')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_walkins', to='Applicant.programs')),
            ],
            options={
                'ordering': ['-completion_date'],
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
