# Generated by Django 5.2.4 on 2025-09-23 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0038_walkinapplication_approvedwalkin_walkinpasser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMSReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('program', 'Program Application'), ('walkin', 'Walk-in Application')], max_length=20)),
                ('application_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('incomplete', 'Incomplete'), ('ready_for_approval', 'Ready for Approval')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('has_id_picture', models.BooleanField(default=False)),
                ('has_learner_profile', models.BooleanField(default=False)),
                ('has_signature', models.BooleanField(default=False)),
                ('has_required_documents', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('missing_documents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_reviews', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_reviews', to='Applicant.programs')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application_type', 'application_id')},
            },
        ),
        migrations.CreateModel(
            name='DMSApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('program', 'Program Application'), ('walkin', 'Walk-in Application')], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending_final_approval', 'Pending Final Approval')], default='pending_final_approval', max_length=30)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_approvals', to='Applicant.programs')),
                ('dms_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='Applicant.dmsreview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
