# Generated by Django 5.2.4 on 2025-09-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0039_dmsreview_dmsapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('manual', 'Manual'), ('policy', 'Policy')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManualDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='documents/manuals/')),
                ('batch', models.CharField(blank=True, choices=[('batch_1', 'Batch 1'), ('batch_2', 'Batch 2'), ('batch_3', 'Batch 3'), ('batch_4', 'Batch 4'), ('batch_5', 'Batch 5')], max_length=20, null=True)),
                ('semester', models.CharField(blank=True, choices=[('semester_1', 'Semester 1'), ('semester_2', 'Semester 2'), ('semester_3', 'Semester 3')], max_length=20, null=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'manual'}, on_delete=django.db.models.deletion.CASCADE, to='Applicant.documentcategory')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Applicant.programs')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_manuals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Document',
                'verbose_name_plural': 'Manual Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='documents/policies/')),
                ('batch', models.CharField(blank=True, choices=[('batch_1', 'Batch 1'), ('batch_2', 'Batch 2'), ('batch_3', 'Batch 3'), ('batch_4', 'Batch 4'), ('batch_5', 'Batch 5')], max_length=20, null=True)),
                ('semester', models.CharField(blank=True, choices=[('semester_1', 'Semester 1'), ('semester_2', 'Semester 2'), ('semester_3', 'Semester 3')], max_length=20, null=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'policy'}, on_delete=django.db.models.deletion.CASCADE, to='Applicant.documentcategory')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Applicant.programs')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
