# Generated by Django 5.2.4 on 2025-09-27 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0040_documentcategory_manualdocument_policydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='program_skill',
        ),
        migrations.AddField(
            model_name='programs',
            name='program_competencies',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='ArchivedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_training_id', models.IntegerField()),
                ('program_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('task_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room_lab', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('examination', 'Examination'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='activity', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_trainings', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Training Session',
                'verbose_name_plural': 'Archived Training Sessions',
                'ordering': ['-archived_at'],
            },
        ),
    ]
