# Generated by Django 5.2.4 on 2025-10-01 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0042_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSemesterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_batch', models.CharField(choices=[('1', 'Batch 1'), ('2', 'Batch 2'), ('3', 'Batch 3')], default='1', max_length=10)),
                ('active_semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester')], default='1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='semester_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Semester Setting',
                'verbose_name_plural': 'Active Semester Settings',
            },
        ),
        migrations.CreateModel(
            name='TrainingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_training_id', models.IntegerField()),
                ('program_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('task_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room_lab', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('examination', 'Examination'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='activity', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_archives', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Archive',
                'verbose_name_plural': 'Training Archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
