# Generated by Django 5.2.4 on 2025-10-01 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0043_activesemestersettings_trainingarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCompetencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_competencies', models.JSONField(blank=True, default=dict)),
                ('common_competencies', models.JSONField(blank=True, default=dict)),
                ('core_competencies', models.JSONField(blank=True, default=dict)),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('common_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('core_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_competencies', to='Applicant.programs')),
            ],
            options={
                'verbose_name': 'Applicant Competency',
                'verbose_name_plural': 'Applicant Competencies',
                'ordering': ['-updated_at'],
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
