# Generated by Django 5.2.4 on 2025-10-01 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0044_applicantcompetencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='batch_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BatchCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_batch', models.CharField(choices=[('1', 'Batch 1'), ('2', 'Batch 2'), ('3', 'Batch 3')], default='1', max_length=10)),
                ('cycle_state', models.CharField(choices=[('waiting_enrollment', 'Waiting for Enrollment Event'), ('enrollment_active', 'Enrollment Event Active'), ('batch_active', 'Batch Active'), ('trimester_1', '1st Semester Active'), ('trimester_2', '2nd Semester Active'), ('trimester_3', '3rd Semester Active'), ('trimester_completed', 'Trimester Completed - Waiting for Next Enrollment')], default='waiting_enrollment', max_length=30)),
                ('current_semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester')], default='1', max_length=10)),
                ('completed_semesters', models.JSONField(blank=True, default=dict)),
                ('batch_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_semester_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_enrollment_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_batch_cycle', to='Applicant.event')),
            ],
            options={
                'verbose_name': 'Batch Cycle',
                'verbose_name_plural': 'Batch Cycles',
                'ordering': ['-created_at'],
            },
        ),
    ]
