# Generated by Django 5.2.4 on 2025-10-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0045_event_batch_activated_batchcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesemestersettings',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activesemestersettings',
            name='completed_semester',
            field=models.CharField(blank=True, choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='activesemestersettings',
            name='semester_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
