# Generated by Django 5.2.4 on 2025-10-11 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0046_activesemestersettings_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSTC_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('applicant_profile', 'Applicant Profile'), ('policy_guidelines', 'Policy and Guidelines')], max_length=50)),
                ('document_file', models.FileField(upload_to='lmstc_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, choices=[('batch_1', 'Batch 1'), ('batch_2', 'Batch 2'), ('batch_3', 'Batch 3'), ('batch_4', 'Batch 4'), ('batch_5', 'Batch 5')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmstc_documents', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lmstc_documents', to='Applicant.programs')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_lmstc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMSTC Document',
                'verbose_name_plural': 'LMSTC Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
