# Generated by Django 5.2.4 on 2025-10-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0047_lmstc_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmstc_documents',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmstc_documents', to='Applicant.learner_profile'),
        ),
    ]
