# Generated by Django 5.2.4 on 2025-10-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0049_supportticket_ticketresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapplicant',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvedapplicant',
            name='enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedwalkin',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvedwalkin',
            name='enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Program Application'), ('approval', 'Application Approval'), ('rejection', 'Application Rejection'), ('program_completion', 'Program Completion')], max_length=20),
        ),
    ]
