# Generated by Django 5.2.4 on 2025-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0050_approvedapplicant_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapplicant',
            name='application_type',
            field=models.CharField(choices=[('online', 'Online'), ('walkin', 'Walk-in')], default='online', max_length=20),
        ),
    ]
