# Generated by Django 5.2.4 on 2025-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0051_approvedapplicant_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedapplicant',
            name='enrollment_semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
