# Generated by Django 5.2 on 2025-10-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0052_approvedapplicant_enrollment_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmstc_documents',
            name='document_type',
            field=models.CharField(choices=[('applicant_profile', 'Applicant Profile'), ('policy_guidelines', 'Policy and Guidelines'), ('modules_manuals', 'Modules and Manuals')], max_length=50),
        ),
    ]
