# Generated by Django 5.2.4 on 2025-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0053_alter_lmstc_documents_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='marked_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
