# Generated by Django 5.2.4 on 2025-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0055_trainerprofile_multiple_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
