# Generated by Django 5.2.4 on 2025-11-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0056_training_batch_number_training_enrollment_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.IntegerField()),
                ('document_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('edit', 'Edit'), ('archive', 'Archive'), ('restore', 'Restore'), ('delete', 'Delete')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Audit Log',
                'verbose_name_plural': 'Document Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
