# Generated by Django 5.2.4 on 2025-11-17 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0057_documentauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_url', models.URLField()),
                ('job_company', models.CharField(blank=True, max_length=255)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-saved_at'],
                'unique_together': {('user', 'job_url')},
            },
        ),
    ]
