# Generated by Django 5.2.4 on 2025-12-01 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0058_savedjobmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProgramSemesterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester')], default='1', max_length=10)),
                ('semester_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('completed_semester', models.CharField(blank=True, choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester')], max_length=10, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_semester_settings', to='Applicant.programs')),
                ('trainer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='program_semester_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Program Semester Setting',
                'verbose_name_plural': 'Trainer Program Semester Settings',
                'unique_together': {('trainer', 'program')},
            },
        ),
    ]
