# Generated by Django 5.2.4 on 2025-12-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0059_trainerprogramsemestersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/'),
        ),
        migrations.AlterField(
            model_name='lmstc_documents',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='lmstc_documents/'),
        ),
    ]
