# Generated by Django 5.2.4 on 2026-01-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0060_staffmember_trainerprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='forwarded_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batchcycle',
            name='cycle_state',
            field=models.CharField(choices=[('waiting_enrollment', 'Waiting for Enrollment Event'), ('enrollment_active', 'Enrollment Event Active'), ('batch_active', 'Batch Active'), ('trimester_1', '1st Semester Active'), ('trimester_2', '2nd Semester Active'), ('trimester_3', '3rd Semester Active'), ('trimester_completed', 'Trimester Completed - Waiting for Next Enrollment'), ('application_blocked', 'Application Blocked - After Batch 3, Waiting for Admin to Open Batch 1')], default='waiting_enrollment', max_length=30),
        ),
    ]
