# Generated by Django 5.2.4 on 2026-01-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0063_adminactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='training_image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
