# Generated by Django 5.2.4 on 2026-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0064_programs_training_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='voter_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/voter_ids/'),
        ),
    ]
